package tg.weatherforcastbackend.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;


@Data
@NoArgsConstructor
@AllArgsConstructor
public class DayForcastDto {
    private float cloudBaseAvg;
    private float cloudBaseMax;
    private float cloudBaseMin;
    private float cloudCeilingAvg;
    private float cloudCeilingMax;
    private float cloudCeilingMin;
    private float cloudCoverAvg;
    private float cloudCoverMax;
    private float cloudCoverMin;
    private float dewPointAvg;
    private float dewPointMax;
    private float dewPointMin;
    private float evapotranspirationAvg;
    private float evapotranspirationMax;
    private float evapotranspirationMin;
    private float evapotranspirationSum;
    private float freezingRainIntensityAvg;
    private float freezingRainIntensityMax;
    private float freezingRainIntensityMin;
    private float humidityAvg;
    private float humidityMax;
    private float humidityMin;
    private float iceAccumulationAvg;
    private float iceAccumulationLweAvg;
    private float iceAccumulationLweMax;
    private float iceAccumulationLweMin;
    private float iceAccumulationLweSum;
    private float iceAccumulationMax;
    private float iceAccumulationMin;
    private float iceAccumulationSum;
    private  String moonriseTime;
    private  String moonsetTime;
    private float  precipitationProbabilityAvg;
    private float  precipitationProbabilityMax;
    private float precipitationProbabilityMin;
    private float pressureSurfaceLevelAvg;
    private float pressureSurfaceLevelMax;
    private float pressureSurfaceLevelMin;
    private float rainAccumulationAvg;
    private float rainAccumulationLweAvg;
    private float rainAccumulationLweMax;
    private float rainAccumulationLweMin;
    private float rainAccumulationMax;
    private float rainAccumulationMin;
    private float rainAccumulationSum;
    private float rainIntensityAvg;
    private float rainIntensityMax;
    private float rainIntensityMin;
    private float  sleetAccumulationAvg;
    private float  sleetAccumulationLweAvg;
    private float  sleetAccumulationLweMax;
    private float  sleetAccumulationLweMin;
    private float sleetAccumulationLweSum;
    private float sleetAccumulationMax;
    private float sleetAccumulationMin;
    private float sleetIntensityAvg;
    private float sleetIntensityMax;
    private float sleetIntensityMin;
    private float snowAccumulationAvg;
    private float snowAccumulationLweAvg;
    private float snowAccumulationLweMax;
    private float snowAccumulationLweMin;
    private float snowAccumulationLweSum;
    private float snowAccumulationMax;
    private float snowAccumulationMin;
    private float snowAccumulationSum;
    private float snowIntensityAvg;
    private float snowIntensityMax;
    private float snowIntensityMin;
    private  String  sunriseTime;
    private  String sunsetTime;
    private float temperatureApparentAvg;
    private float temperatureApparentMax;
    private float temperatureApparentMin;
    private float temperatureAvg;
    private float temperatureMax;
    private float  temperatureMin;
    private float uvHealthConcernAvg;
    private float uvHealthConcernMax;
    private float uvHealthConcernMin;
    private float uvIndexAvg;
    private float uvIndexMax;
    private float uvIndexMin;
    private float visibilityAvg;
    private float visibilityMax;
    private float visibilityMin;
    private float weatherCodeMax;
    private float weatherCodeMin;
    private float windDirectionAvg;
    private float windGustAvg;
    private float windGustMax;
    private float windGustMin;
    private float windSpeedAvg;
    private float windSpeedMax;
    private float windSpeedMin;
}
